version: '3'
services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car_catalog
    ports:
      - "5434:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
